# Generated by Django 3.2.25 on 2024-10-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
    ]
