# Generated by Django 3.2.25 on 2024-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='responses',
        ),
    ]
