# Generated by Django 3.2.25 on 2024-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_answer_answer_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='가대생', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='010-0000-0000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room_capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
